- src/Form/MemberDetailsType.php
- templates/user/details.html.twig
Vanzelfsprekende titel, een lid kan nu zelf een afdeling kiezen.
Closes #72
> Add ability to choose division

- templates/email/html/welcome.html.twig
Signed-off-by: Andrew Ammerlaan <andrewammerlaan@gentoo.org>
> email/html/welcome.html.twig: make links clickable

- src/Entity/Member.php
> Put back setNewPasswordToken function

- .env
- config/services.yaml
Based on https://symfony.com/doc/current/security/force_https.html
Signed-off-by: Andrew Ammerlaan <andrewammerlaan@gentoo.org>
> allow forcing http/https

- config/packages/security.yaml
https://github.com/roodjong/mijnrood/pull/86 didn't quite do the trick, lets try this
Signed-off-by: Andrew Ammerlaan <andrewammerlaan@gentoo.org>
> allow forcing http/https (2)

- docker/prod/Dockerfile
- package.json
- yarn.lock
> Fix routing js

- docker/prod/docker-compose.yml
This is already running on prod, and it seems to work well
> Restart docker containers unless stopped

- docker/prod/docker-compose.yml
> Remove useless key in docker compose

- .env
- config/packages/framework.yaml
- config/packages/security.yaml
- config/services.yaml
- src/Controller/Admin/DashboardController.php
- src/Controller/Security/ExternalAuthCheckController.php
Je kan listmonk instellen dat ie nginx gebruikt voor auth via [nginx external auth](https://developer.okta.com/blog/2018/08/28/nginx-auth-request)
> Add external auth check for nginx

- src/Controller/DocumentsController.php
> Sort folders and files

- README.md
Bug: https://github.com/roodjong/mijnrood/issues/120
> README.md: add deprecation notice

- templates/division/members.html.twig
Volgens mij lost dit het probleem op waardoor sommige mensen niet hun groepen pagina konden bekijken. Ik wacht nog op een antwoord van Gijs om te confirmen dat dit nu klopt
> Fix optional template variable

- docker/prod/php.ini
> Increase cookie lifetime

- .env
- README.md
- config/services.yaml
- migrations/Version20240305203045.php
- src/Controller/Admin/MemberCrud.php
- src/Controller/Admin/MembershipApplicationCrud.php
- src/Controller/MemberController.php
- src/DataFixtures/MemberFixtures.php
- src/Entity/Member.php
- src/Entity/MembershipApplication.php
- src/Form/MembershipApplicationType.php
- templates/email/html/contact_new_member.html.twig
- templates/email/html/request_new_password.html.twig
- templates/email/text/contact_new_member.txt.twig
- templates/email/text/request_new_password.txt.twig
- templates/user/member/apply.html.twig
> [143] Add middle names

- composer.lock
- docker/prod/Dockerfile
- package.json
- yarn.lock
- updates node from 18 to 20 in prod to match dev
- updates php to 8.2 in prod to match dev
- update various js/php modules to resolve open security issues 
- add COMPOSER_ALLOW_SUPERUSER=1, since we run as root in the docker container
> Docker: yarn+composer updates and sync dev with prod

- .env
- config/services.yaml
- src/Controller/Admin/DashboardController.php
It is not used by any of the organizations.
> Remove listmonk item

- src/Controller/Admin/MemberCrud.php
- src/Entity/Member.php
Also added membership type to Excel export.
> [SCOUT] Fix members page for contact people being broken

- src/Controller/Admin/MembershipApplicationCrud.php
> [189] Fix membership application filter

- src/Controller/Admin/MemberCrud.php
Very primitive way of cancelling subscriptions. Not a fancy solution but given the urgency I opted for a lesser-than-ideal approach.
> Add membership cancellation for Mollie

- composer.lock
- docker/php/Dockerfile
- yarn.lock
And mark our git dir safe in the docker container so we can run git inside the container.
> *.lock: update dependencies

- templates/user/member/failed.html.twig
- templates/user/member/finished.html.twig
- templates/user/member/processing.html.twig
> Use variable org logo instead of hardcoded

- src/Entity/Member.php
- templates/user/details.html.twig
> Sort payments correctly

- config/packages/security.yaml
Blijkbaar stond deze optie er al in, maar uit.
Misschien dat er een reden voor was?
closing #122
> 122 redirect to requested page after login

- templates/user/details.html.twig
We automatically put the member ID in the subject for convenience
Closes: https://github.com/roodjong/mijnrood/issues/229
> details.html.twig: add note and link on how to deregister

- src/Controller/Admin/MemberCrud.php
> [202] Add middle name to export

- src/Controller/ContributionController.php
- src/DataFixtures/SupportMemberFixtures.php
- src/Form/Contribution/ContributionIncomeType.php
- templates/user/contribution/automatic-collection-change.html.twig
- templates/user/contribution/automatic-collection.html.twig
- templates/user/member/apply.html.twig
- templates/user/support_member/apply.html.twig
Default html validation will require you to put in atleast the minimum amount. Backend will if filled in check if greaterthan, if value is null it will throw a form error.
closes: https://github.com/roodjong/mijnrood/issues/166
> feat(contribution): added validation on custom contribution amount

- templates/user/support_member/apply.html.twig
> removed test text
